SELECT "INTERVALSTARTTIME_GMT", "INTERVALENDTIME_GMT", "MW", "OPR_HR"
FROM "2018"

UNION ALL

SELECT "INTERVALSTARTTIME_GMT", "INTERVALENDTIME_GMT", "MW", "OPR_HR"
FROM "2019"

UNION ALL

SELECT "INTERVALSTARTTIME_GMT", "INTERVALENDTIME_GMT", "MW", "OPR_HR"
FROM "2020"

UNION ALL

SELECT "INTERVALSTARTTIME_GMT", "INTERVALENDTIME_GMT", "MW", "OPR_HR"
FROM "2021"

CREATE TABLE "2018" (
    "INTERVALSTARTTIME_GMT" timestamp,
    "INTERVALENDTIME_GMT" timestamp,
    "MW" decimal,
    "OPR_HR" int
);

CREATE TABLE "2019" (
    "INTERVALSTARTTIME_GMT" timestamp,
    "INTERVALENDTIME_GMT" timestamp,
    "MW" decimal,
    "OPR_HR" int
);

CREATE TABLE "2020" (
    "INTERVALSTARTTIME_GMT" timestamp,
    "INTERVALENDTIME_GMT" timestamp,
    "MW" decimal,
    "OPR_HR" int
);

CREATE TABLE "2021" (
    "INTERVALSTARTTIME_GMT" timestamp,
    "INTERVALENDTIME_GMT" timestamp,
    "MW" decimal,
    "OPR_HR" int
);